name: test-connect-sdk-examples
permissions:
  packages: read
  contents: read
  pull-requests: write
  issues: write
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENVIRONMENT: test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "connect/sdk/**"
jobs:
  test-javascript-example:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./connect/sdk/javascript-example
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"
      - name: Install root tools
        working-directory: ./
        run: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
